variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

debian_10:
  stage: build
  image: debian:10
  script:
    - "sudo apt install libopencv-dev libpugixml-dev libpangocairo-1.0-0 libpango1.0-dev libcairo2-dev clang make python3 git python3-wheel curl python3-pip python3-venv"
    - "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
    - "source $HOME/.cargo/env"
    - "rustup install stable"
    - "rustup default stable"
    - "cargo install usvg"
    - "pip3 install --user git+https://git.jaseg.de/pcb-tools-extension.git"
    - "pip3 install --user gerbolyze --no-binary gerbolyze"
    - "gerbolyze --help"

ubuntu_2004:
  stage: build
  image: ubuntu:20.04
  script:
    - "sudo apt install libopencv-dev libpugixml-dev libpangocairo-1.0-0 libpango1.0-dev libcairo2-dev clang make python3 git python3-wheel curl python3-pip python3-venv cargo"
    - "cargo install usvg"
    - "pip3 install --user git+https://git.jaseg.de/pcb-tools-extension.git"
    - "pip3 install --user gerbolyze --no-binary gerbolyze"
    - "gerbolyze --help"

fedora_33:
  stage: build
  image: fedora:33
  script:
    - "dnf --nodocs --assumeyes --refresh install python3 python3-pip git make clang opencv-devel pugixml-devel pango-devel cairo-devel rust cargo python3-numpy python3-slugify python3-lxml python3-click"
    - "cargo install usvg"
    - "export PATH=$HOME/.cargo/bin:$PATH"
    - "pip3 install --user git+https://git.jaseg.de/pcb-tools-extension.git"
    - "python3 setup.py install --user"
    - "export PATH=$HOME/.local/bin:$PATH"
    - "gerbolyze --help"

archlinux:
  stage: build
  image: archlinux:latest
  script:
    - "pacman -Syyu --needed --noconfirm --noprogressbar base-devel pugixml opencv pango cairo git python python-pip make clang rustup cargo pkgconf python-numpy python-slugify python-lxml python-click"
    - "rustup install stable"
    - "rustup default stable"
    - "cargo install usvg"
    - "pip install --user git+https://git.jaseg.de/pcb-tools-extension.git"
    - "python setup.py install --user"
    - "export PATH=$HOME/.local/bin:$PATH"
    - "gerbolyze --help"

