variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

debian_10:
  stage: build
  image: "registry.gitlab.com/gerbolyze/build-containers/debian:10"
  script:
    - "export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH CXX=clang++"
    - "python3 setup.py install --user"
    - "gerbolyze --help"

ubuntu_2004:
  stage: build
  image: "registry.gitlab.com/gerbolyze/build-containers/ubuntu:20.04"
  script:
    - "export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH CXX=clang++"
    - "python3 setup.py install --user"
    - "gerbolyze --help"

fedora_33:
  stage: build
  image: "registry.gitlab.com/gerbolyze/build-containers/fedora:33"
  script:
    - "export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH CXX=clang++"
    - "python3 setup.py install --user"
    - "gerbolyze --help"

archlinux:
  stage: build
  image: "registry.gitlab.com/gerbolyze/build-containers/archlinux:latest"
  script:
    - "export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
    - "python setup.py install --user"
    - "gerbolyze --help"

